### ISSUE TITLE
Some games fail to download  (fallout new vegas, bioshock infinite)

### ISSUE THREAD

**Issue by nsilvias** [hawkeye116477/playnite-legendary-plugin#10]
this seems to be an issue relating to language download options not being inplemented in the extension? i thought it was a one off with bioshock infinite when this extension first released but the recent fallout new vegas giveaway had this same problem.

**Comment by hawkeye116477** [comment]
> issue relating to language download options not being inplemented

Legendary calls that selective downloads. That's already added in code, only update not released yet. I just need to check few things yet and I think that I will release it by the end of month or little faster.
