### ISSUE TITLE
Fullscreen download list clearing

### ISSUE THREAD

**Issue by DankestMemeLord** [hawkeye116477/playnite-legendary-plugin#104]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-legendary-plugin/issues) to make sure that this feature hasn't been requested before .

### Is your feature request related to a problem? Please describe.

This is related to full-screen support. 

When attempting to download a game that isn't installed on your system but is still saved in the downloads list, you get the popup saying the game is currently in the download list already.

This is a problem if you are attempting to reinstall a game you've recently deleted. As far as I know full-screen mode doesn't have any way to access the sidebar and clear them before attempting to re-download.

To recreate:
- Install a game in your legendary library
- Uninstall the game
- Attempt to reinstall the game

Thank you for all of the work you do <3

### Describe the solution you'd like

Either automatically clearing completed downloads, or clearing completed downloads before attempting to install games.

### Describe alternatives you've considered

- Setting/toggle to automatically clearing completed downloads
- Add a button to the popup with the option to clear it, if it's completed
- Toggle/setting to disable the popup and attempt to install games regardless

### Additional context

![Screenshot 2024-11-16 154503](https://github.com/user-attachments/assets/9902ba4e-20a3-4cf4-a643-7e799450be9e)
![Screenshot 2024-11-16 155336](https://github.com/user-attachments/assets/0e588521-14ad-4dfe-bca3-ce0c0268dcc7)
The game is in the list, however it is not currently installed.

**Comment by hawkeye116477** [comment]
Yeah, unfortunately full screen mode of Playnite is very limited for extensions. 
I think that the best I can do would be to remove it from list if it's not installed. 
Option to add possibility to auto clear completed downloads just like it's done similar for cache also seems good.
I'll probably add both :smile:.
