### ISSUE TITLE
Game Updating

### ISSUE THREAD

**Issue by SkyNinja** [hawkeye116477/playnite-legendary-plugin#19]
### Is your feature request related to a problem? Please describe.

When trying to launch an outdated game, you currently just get an error. The 'Repair' option also doesn't seem to cover updating. Because of this, you have to either uninstall and reinstall entirely or go outside playnite to update.

### Describe the solution you'd like

Since there doesn't seem to be a method for checking for updates, a manual context menu action calling install with --update-only or --repair-and-update would handle it fine.

### Describe alternatives you've considered

Currently, I use the CLI to update unless it's a very small game.

**Comment by koxx12-dev** [comment]
Kinda bizarre why its not automatic, when legendary explicitly states when a game it not up to date on launch. 
Skipping updates could be also added as a per game toggle if you are in offline mode (`--skip-version-check` on launch)
