### ISSUE TITLE
Button to clear completed downloads

### ISSUE THREAD

**Issue by darklinkpower** [hawkeye116477/playnite-legendary-plugin#24]
### Is your feature request related to a problem? Please describe.

Currently downloads have to be removed one by one

### Describe the solution you'd like

A button to clear all completed downloads would be very helpful

### Additional context

The button should go around here

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/d25f44d6-9e2b-492a-9f95-9d38ef5192b9)

**Comment by hawkeye116477** [comment]
> Currently downloads have to be removed one by one

Theoretically it's possible to use filter button, select "completed", press "ctrl+a" and then trash button to remove, but it asks for confirmation separately for each entry. I'm not sure if button to clear all is really needed if filtering is possible, but can add button to select all entries and make one confirmation dialog for all.

**Comment by darklinkpower** [comment]
Yeah I saw that you can select all, then press delete and confirm one by one but in my opinion that's not very intuitive and I think the solution you are proposing is not ideal for the same reason. I don't know if you've used download managers but they always have a button to clear completed for ease of use and simplicity, some having a confirmation dialog when clicking and also game clients like Steam and others have buttons to clear finished downloads.

Steam example:

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/dac5bafc-afb8-48f4-80b4-33198def7c4d)

**Comment by hawkeye116477** [comment]
Ok, I did what both of us talked, only I wasn't sure what icon should be for button to remove completed downloads, for now added 🧹 icon.

**Comment by darklinkpower** [comment]
Hi, I apologize if I'm blind but where are the buttons located? I'm not seeing them 😅

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/213b48b1-249f-415d-a56c-a77a0c1ede18)

**Comment by hawkeye116477** [comment]
Well, to see button you need to load extension from source, cuz it's not yet released.

**Comment by darklinkpower** [comment]
Oh my bad, I thought it was already available in the current release because I updated to a new version after this issue was closed
