### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by darklinkpower** [hawkeye116477/playnite-legendary-plugin#25]
### Plugin's version

1.1.2

### Playnite's version

10.20

### Bug description

I'm not sure if I'm missing something or if it's not supported but the Epic overlay is not available in the games

### Relevant log

Logs don't contain any reference to the plugin when launching the game

### Screenshots

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/f636de4e-8047-434d-a04b-bd0cb31161c4)

**Comment by hawkeye116477** [comment]
Well, as far as I know not all games support EOS Overlay. I see that's installed and enabled, so all should be fine if you didn't checked that you want to launch games in offline mode.

**Comment by darklinkpower** [comment]
I forgot to close the issue but the overlay worked in another (newer) game.
