### ISSUE TITLE
Account Authentication Broken

### ISSUE THREAD

**Issue by Kamaad1** [hawkeye116477/playnite-legendary-plugin#29]
### Plugin's version

1.1.3

### Playnite's version

10.20

### Bug description

Tried to connect my Epic Games account to the plugin and authenticate but authentication is totally broken. Tried restarting, deleting the config file and re-installing the extension. Nothing works.

### Relevant log

Error message says 'Failed to authenticate user'

### Screenshots

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/101988423/ff403137-a085-4f70-83fe-4c64fc96a3e9)

**Comment by hawkeye116477** [comment]
How you login, using Sony account or some other or Epic?

**Comment by Kamaad1** [comment]
Tried logging in through a linked account and just typing in my details. Neither worked.

I'm just using Heroic launcher. From what I could gather, this extension would work with it.

**Comment by hawkeye116477** [comment]
Try updating Heroic. Check also log files in `%APPDATA%\Playnite`.

**Comment by Kamaad1** [comment]
Yep, that worked perfectly. I was using the portable installation of Heroic instead. Just as a suggestion, maybe add that somewhere in the read me? Just to prevent anyone not realising like I did.

**Comment by hawkeye116477** [comment]
I didn't pay attention to portable Heroic before. Thanks for advice. I added that now to [Troubleshooting](https://github.com/hawkeye116477/playnite-legendary-plugin/wiki/Troubleshooting).
