### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by Smgit5** [hawkeye116477/playnite-legendary-plugin#31]
### Playnite's version

10.20

### Plugin's version

1.1.3

### Legendary Launcher version

?

### Bug description

When I try to authenticate, it is giving me an error "Failed to authenticate user". It has imported the installed game, but due to the authentication error it cannot import the other games. OS - Windows 10. I installed legendary by downloading the legendary.exe from github. I was trying to authenticate by entering my epic account email and password.

### Relevant log

The error message is "Failed to authenticate user".

### Screenshots

![Screenshot (6)](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/94289238/8889b3c4-6334-4873-98b1-42284e44f895)

![Screenshot (7)](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/94289238/f66f65a4-70e2-4f80-b8de-3ba2f0fe2fa3)

Following is the location where legendary.exe is stored:
![Screenshot (8)](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/94289238/dd8d8f76-a28e-47f6-bb91-5c437c3e5242)

**Comment by hawkeye116477** [comment]
Legendary binary needs to be at specific places mentioned at https://github.com/hawkeye116477/playnite-legendary-plugin/wiki/Troubleshooting#legendary-launcher-is-not-installed. Otherwise correct path to legendary binary needs to be added to Advanced plugin settings or PATH environment variable. Have you done it? If yes, then show me log files content from `%APPDATA%\Playnite`.

**Comment by Smgit5** [comment]
Hey, sorry for the late reply, and thank you! Adding the custom path in the advanced setting worked!

**Comment by hawkeye116477** [comment]
You're welcome. As I see, it's another similar problem reported, so that will be "fixed" in the next version by adding more checking if user has Legendary Launcher installed, so itll be clear what is that problem.
