### ISSUE TITLE
Toggle for Playtime sync

### ISSUE THREAD

**Issue by BrutuZ** [hawkeye116477/playnite-legendary-plugin#41]
### Is your feature request related to a problem? Please describe.

With the Playnite Setting _"Import playtime of games in library"_ set to _"Always"_ the playtime for the EGS games gets reset after every library sync, and we lose the time tracked by Playnite itself.

### Describe the solution you'd like

A toggle under settings to disable playtime syncing and the resulting overwriting.

### Describe alternatives you've considered

If the plugin has access to the Playnite entry's playtime it could compare it to the time reported by Legendary and use whichever is greater.

### Additional context

Related issues: #6 and https://github.com/derrod/legendary/issues/502

**Comment by hawkeye116477** [comment]
Both solutions seems great. However in case of second solution, I'd need to add searching for that in Playnite's database and I'm afraid that could cause much slower importing.
So for now I'll add toggling. Besides global switch, there will be also possible to change that per game.
I'll set syncing playtime as disabled by default.
