### ISSUE TITLE
Dialog being displayed when starting or closing game

### ISSUE THREAD

**Issue by darklinkpower** [hawkeye116477/playnite-legendary-plugin#45]
### Playnite version

10.32

### Plugin version

1.4.0

### Legendary Launcher version

0.20.34

### Bug description

A dialog saying "Downloading Metadata" is being displayed when a game is started or when it is stopped. This happens to all games, even the ones not imported by this plugin.

### Relevant log

Nothing about the plugin available in logs

### Screenshots

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/bc6063c5-9db5-4156-a6c8-090a89118014)

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/5c8f2c45-01f5-45dd-aa09-d03a5feea9f6)

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/6453c74d-3e7c-4673-9294-2d5d45f52ec0)

**Comment by hawkeye116477** [comment]
It's not a bug, but "feature". Cloud saves feature needs to know where game saves are located, so it downloads that info if cached file isn't available.

**Comment by darklinkpower** [comment]
I apologize but it wasn't clear to me in your reply, is it intended that this process also happens in games not imported by this plugin? Like manually added games, Steam, GOG, etc. I can't think of a reason for that if that's the case but I might be missing something.

**Comment by hawkeye116477** [comment]
> I apologize but it wasn't clear to me in your reply, is it intended that this process also happens in games not imported by this plugin?

No, initially apparently I didn't read second part. It wasn't intended. Anyway, I fixed that in linked last commit.
