### ISSUE TITLE
Extension not working after 1.7.0 update.

### ISSUE THREAD

**Issue by wensleyoliv** [hawkeye116477/playnite-legendary-plugin#56]
### Playnite version

10.32

### Plugin version

1.7.0

### Legendary Launcher version

0.20.34

### Bug description

When i open playnite the plugin can't import games and gives the error: errors.com.epicgames.common.oauth.invalid_token. And if i go to the plugin settings the program crashes asking for a restart.

### Relevant log

[playnite log.zip](https://github.com/hawkeye116477/playnite-legendary-plugin/files/14530868/playnite.log.zip)

### Screenshots

![error](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/14226926/3d74e33c-8e24-4325-8b87-3790a2a77460)
![crash](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/14226926/14609be5-7172-4068-9035-82e215f91c36)

**Comment by hawkeye116477** [comment]
Ah, looks like you had invalid/expired token, which can't be renewed. You can extract attached zip and drag and drop pext to Playnite's window to check if my fix is working :smile:.

[LL_1.7_fix.zip](https://github.com/hawkeye116477/playnite-legendary-plugin/files/14531294/LL_1.7_fix.zip)

**Comment by wensleyoliv** [comment]
It worked! Thank you very much.
