### ISSUE TITLE
Right click game menu shows a lot of items if multiple items are selected

### ISSUE THREAD

**Issue by darklinkpower** [hawkeye116477/playnite-legendary-plugin#59]
### Playnite version

10.32

### Plugin version

1.7.1

### Legendary Launcher version

0.20.34

### Bug description

I don't know if it's intended but selecting multiple items shows a lot of items in the right click menu and I think it's not clear and there are possible improvements:

1. Move items to their own "Legendary Library" submenu to make it clearer that these actions belong to the plugin
2. Show these items when only 1 game is selected because currently it's not very friendly seing too many items there and also don't know to which game each one belongs. Keeping it simple would be better in my opinion.
For an installed game:
![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/70db09d5-9365-44f1-b5f5-2f2f9b5d6d9e)
For an uninstalled game:
![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/61f0283a-63c9-4985-be8c-6bc0237f3756)

Not showing all items would also help to improve performance because currently there's a small freeze due to adding to many items to the menu

### Relevant log

-

### Screenshots

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/6a79e910-2937-4536-b0aa-3e06f4ed97bc)

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/a2781ac1-75e2-422b-8760-7e41347d842a)

**Comment by hawkeye116477** [comment]
Thanks for report. That wasn't intended of course.
