### ISSUE TITLE
Confusing update message on startup

### ISSUE THREAD

**Issue by darklinkpower** [hawkeye116477/playnite-legendary-plugin#65]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-legendary-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.33

### Plugin version

1.7.4.41039

### Legendary Launcher version

0.20.34

### Bug description

I got this update notification window on startup after disabling my PC internet and restarting it.

The window displays some of my games with a `0` after them, which I guess it's supposed to be the game update size. My guess is that the plugin tried to check for game updates and failed to fetch correctly if there was an update because there was no internet but mistakenly identified that there were updates available with 0 size.

### Relevant log

I forgot about it and deleted my log yesterday that contained the logs after this happened. Let me know if it's needed to try to reproduce it again.

### Screenshots

![Playnite DesktopApp_yZdvdIy55k](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/22ee2f5f-e1f6-4cb3-905f-f04e1351df48)

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/1389286/69fde777-e030-4f25-a86c-12a2433a3fc9)

**Comment by hawkeye116477** [comment]
Thanks for report, I'll see what can be done.

> some of my games with a 0 after them, which I guess it's supposed to be the game update size. 

0 is version number.
