### ISSUE TITLE
EA Game doesnt launch. EA APP Activation button doesnt detect games or initiate a setup. 

### ISSUE THREAD

**Issue by nsilvias** [hawkeye116477/playnite-legendary-plugin#67]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-legendary-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.33

### Plugin version

1.7.5

### Legendary Launcher version

0.20.34

### Bug description

Hi there, Today EGS gave away an EA game called Dragon Age Inquisition. This is the first EA game ive added to my EGS account and the game will not launch. The game is linked to my EA account but when i launch it doesnt see playnite. EA APP tells me its looking for EGS. In Legendary Epic Plugins settings ived attempted to use the activate button under EA App and it tells me that there is no EA games nor does it show me a setup process. I logged out and logged back into my EGS account in the Legendary Epic plugin settings and this does not resolve the issue. the ubisoft activate games button works fine like it always has for me but not the EA activate one. perhaps EA games acquired thru EGS need EGS to be installed unlike ubisoft games? 

### Relevant log

"No availible EA games" after clicking activate games buttons in plugin settings. not even a set up process.

**Comment by hawkeye116477** [comment]
> perhaps EA games acquired thru EGS need EGS to be installed unlike ubisoft games?

It's not required. Looks like this is same problem as https://github.com/derrod/legendary/pull/632, so it'll be fixed in legendary. However I'll also try to fix that by myself.

**Comment by hawkeye116477** [comment]
Ok, small update.
Just install new version of plugin, then go to advanced settings and clear cache and then try activating again.
