### ISSUE TITLE
Posibility of displaying game name instead of store name in banner

### ISSUE THREAD

**Issue by r3tr0g4m3r** [hawkeye116477/playnite-legendary-plugin#7]
Using the cover view the hover banner shows the store name instead of the game name, could be a feature if feasible.

**with Legendary plugin (LegendaryLibrary_1_0_0.pext):**
![imagen](https://user-images.githubusercontent.com/3663416/235283034-1a54d97a-0567-456e-bda5-3b5e38cf6163.png)

**with Playnite normal game integration:**
![imagen](https://user-images.githubusercontent.com/3663416/235283130-175ed1ed-dbac-4a3a-9fd1-82128d20a0c8.png)

Playnite version: 10.14
API 2.5.0
Theme: Standard X

**Comment by hawkeye116477** [comment]
From what I see at https://github.com/TheKersalMassive/StandardX#how-do-i-get-the-launcher-text-when-a-game-is-selected, this is feature of theme, so I think that you should rather ask theme's author about that.

**Comment by r3tr0g4m3r** [comment]
Feature of theme, not of plugin.
