### ISSUE TITLE
Rare support

### ISSUE THREAD

**Issue by Hunam6** [hawkeye116477/playnite-legendary-plugin#71]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-legendary-plugin/issues) to make sure that this feature hasn't been requested before .

### Describe the solution you'd like

I'm only guessing that since Rare (https://github.com/RareDevs/Rare) is using Legendary, it may be possible to add support for Rare too.

### Describe alternatives you've considered

I may didn't found the way to do this already, maybe you support this already.

**Comment by hawkeye116477** [comment]
It's using precompiled legendary instead of compiled version like Heroic, so I'm afraid that won't be possible.
