### ISSUE TITLE
Doesn't Import Installed Games

### ISSUE THREAD

**Issue by AlanDunaway** [hawkeye116477/playnite-legendary-plugin#72]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-legendary-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.33

### Plugin version

1.7.6

### Legendary Launcher version

NA

### Bug description

I have a few Epic installed games, but Legendary in Playnite isn't showing installed games in the Installed filter option. Picture 1 shows my Epic launcher installed games. Pic 2's Legendary library filter. Pic 3 the library name in focus.

### Relevant log

NA

### Screenshots

![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/96152972/bae93c15-1425-4b1d-8114-ad939344a7c4)
![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/96152972/71f8195a-eead-4884-8bf4-80dc4186e1bf)
![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/96152972/008df972-73e6-40d5-9d31-a1cede443b32)

**Comment by hawkeye116477** [comment]
If they're installed with Epic launcher, then you need to import them manually (right click on game and click import) or do like described at https://github.com/hawkeye116477/playnite-legendary-plugin/wiki/Troubleshooting#games-installed-by-epic-launcher-not-detected-as-installed.

**Comment by AlanDunaway** [comment]
I've set up the integration by logging in to Epic through the library setup screen.

**Comment by hawkeye116477** [comment]
Ok, so I assume it works fine now?
