### ISSUE TITLE
Nothing is downloading. Neither games nor the EOS overlay now.

### ISSUE THREAD

**Issue by cyanites62** [hawkeye116477/playnite-legendary-plugin#73]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-legendary-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.33.0.16167

### Plugin version

1.7.6.39050

### Legendary Launcher version

0.20.34

### Bug description

For some reason, I can't download anything. All is listed as "queued". What do I do?

### Relevant log

I don't know where to find the log for this specific issue, but it just says "queued".

### Screenshots

![legendary](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/169425417/7f2f1a59-fb1e-4898-ab80-5132de5d1acf)

**Comment by hawkeye116477** [comment]
Just click to open log files path and here you should have playnite and extension log files.

**Comment by cyanites62** [comment]
![image](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/169425417/6e0142ea-3fa0-41b1-95ff-8bfcfe126309)
only the config popped up.

**Comment by cyanites62** [comment]
UPDATE: I tried Heroic, uninstalled it cuz it didn't support Playnite, then reinstalled Playnite and Legendary and somehow it worked. Must be an issue with CDNs.

**Comment by hawkeye116477** [comment]
Well, I need to **see log files content from %APPDATA%\Roaming\Playnite.** 

Otherwise I could only guess that maybe your AV likes doing pranks for you, cuz some of them can block legendary and/or Heroic.

> Legendary, Nile and gogdl are all python programs packaged using pyinstaller.
> Since python code is in plain text, anti virus programs flag it after seeing it makes http connections. This is a false positive

**Comment by cyanites62** [comment]
Heroic otherwise works fine. I guess this is an issue with the way I installed this.
