### ISSUE TITLE
Crash when trying to play game without correct legendary binary

### ISSUE THREAD

**Issue by KellaAkella** [hawkeye116477/playnite-legendary-plugin#74]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-legendary-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.33

### Plugin version

1.7.6

### Legendary Launcher version

NA

### Bug description

After I click the Play button, an error message appears. 

### Relevant log

[extensions.log](https://github.com/user-attachments/files/16132249/extensions.log)
[playnite.log](https://github.com/user-attachments/files/16132250/playnite.log)

### Screenshots

![Playnite DesktopApp_7hh7AUxjRY](https://github.com/hawkeye116477/playnite-legendary-plugin/assets/145648512/b2304b87-9c52-47c6-ad40-03e8a56b3d06)

**Comment by hawkeye116477** [comment]
Well, from log looks like for some reason it tries to execute command `launch 41869934302e4b8cafac2d3c0e7c293d` without provided legendary binary. Are you sure you correctly installed legendary as described at https://github.com/hawkeye116477/playnite-legendary-plugin/wiki/Troubleshooting#legendary-launcher-is-not-installed?

**Comment by KellaAkella** [comment]
Sorry, now I did everything right (installed legendary through pip), and it's OK now. Games running.
