### ISSUE TITLE
"Failed to import games from Legendary (Epic). User is not authenticated."

### ISSUE THREAD

**Issue by brh150** [hawkeye116477/playnite-legendary-plugin#8]
It seems that playnite legendary plugin can't refresh token after it "expires_at" time in user.json file at "\.config\legendary\", and thus playnite is welcoming me with above notification. I am able to authenticate through plugin's configuration, but after token's expiration date authentication needs to be repeated. I do also have installed Heroic Launcher (not starting with system) and instead of manual authentication through plugin's configuration I can just run Heroic Launcher which updates user.json file automatically and thus playnite legendary plugin no longer requires authentication.

I don't know if this is of any use, but I've tried putting standalone version of legendary .exe in "Program Files\Legendary\", use custom launcher path in plugin's configuration and installing legendary through pip. None of this helped me with authentication issue.

Am I doing something wrong here or is it expected behavior? I've started to use playnite recently as GOG Galaxy substitution. Also never used Legendary Launcher before (or Heroic Launcher).

**Comment by hawkeye116477** [comment]
Thanks for report. I'll fix that in next version.

**Comment by brh150** [comment]
Thank you. Looking forward for the update.

**Comment by hawkeye116477** [comment]
I'll probably release next version at this week or next. In the meantime I've beta version for you.
[LL_beta.zip](https://github.com/hawkeye116477/playnite-legendary-plugin/files/11464906/LL_beta.zip)

**Comment by brh150** [comment]
Thank you, I'll give it a try. I'm away this weekend, but when I'm back I'll report back how it's working.

But for now I have installed beta version, made new authentication through plugin's configuration and user.json file states "expires_at": "2023-05-12T23:20:17.192Z", so I'm going to check after, if the token will renew and authentication remain.

**Comment by brh150** [comment]
Quick info. Yesterday around 23:30 I relaunched playnite and I was still authenticated (user.json didn't update). Today around 5:00 playnite launched with system boot and authentication remained (user.json file got updated - I have library update enabled at every startup). So far so good.

**Comment by brh150** [comment]
After 36h since the last time I've launched playnite it's working - user.json file got updated and authentication remained.👍
