### ISSUE TITLE
Epic Launcher is not installed error when attempting to install an epic game

### ISSUE THREAD

**Issue by Marwans12** [hawkeye116477/playnite-legendary-plugin#95]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-legendary-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.9.4.684

### Legendary Launcher version

0.20.34

### Bug description

When I try to install any game from epic, I get a message "Cannot install game: Epic launcher is not installed", and it's true.
However, Legendary is installed and functional. I am able to download games from it.
The path to Legendary should be correct, as I can go to  
Playnite_Logo > 3rd party clients > Legendary epic 
and it would open the legendary executable.

Other details:
I have installed legendary using pip and uninstalled it a couple of times. Currently I am only using the .exe executable. 
I have installed the playnite plugin from the releases tab on github.

### Relevant log

"Cannot install game: Epic launcher is not installed"
I am not aware of any other relevant log files.

### Screenshots

![image](https://github.com/user-attachments/assets/44e4b81f-cd13-4458-8a75-5e014adc348b)

**Comment by hawkeye116477** [comment]
There is no such error message at my plugin. Most likely you selected game from wrong library (should be `Legendary (Epic)`, not `Epic`.

**Comment by Marwans12** [comment]
You are absolutely correct. 
You might want to add some notes about this in main page or the issues section, because it's not very clear. Unless it's common knowledge for those who are familiar with playnite, then it's my issue.

And thanks a lot for the plugin ❤️
