### ISSUE TITLE
Incorrect file size and download speed

### ISSUE THREAD

**Issue by tabtomi8** [hawkeye116477/playnite-legendary-plugin#96]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-legendary-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.9.4.684

### Legendary Launcher version

0.20.34

### Bug description

In the download manager window, legendary shows the game size for Ghostwire Tokyo incorrectly (2.2 TB instead of 22 GB), and it shows the download speed incorrectly as well (~6 GB/s, I have a 1 Gbps network card).

### Relevant log

[extensions.log](https://github.com/user-attachments/files/17601167/extensions.log)
[playnite.log](https://github.com/user-attachments/files/17601168/playnite.log)

### Screenshots

![image](https://github.com/user-attachments/assets/d69e54e2-ca05-4bf6-ab55-f8b51d1368d2)

**Comment by hawkeye116477** [comment]
Hmm, that's weird I see it correctly. Maybe that's related with region, I'll see that later.
What region you have on Windows?

**Comment by tabtomi8** [comment]
Hungary

**Comment by hawkeye116477** [comment]
So it should be correctly. It's same format as my country.  I think something might be messed up at your OS. Show me additional settings from region settings or try resetting them.
<img src="https://dennisspan.com/wp-content/uploads/2018/06/Configuring-Regional-Settings-and-locales-with-Group-Policy-Regional-Settings-Format-tab.jpg">

**Comment by tabtomi8** [comment]
I've resetted it, and it worked. The problem was that the digit grouping symbol was set to dot. Though this only happenned now, before the last update, it showed it correctly.
![image](https://github.com/user-attachments/assets/5efb7183-e8e1-4e17-addd-89cdc1ae5ae8)

**Comment by hawkeye116477** [comment]
Ok. Anyway I found solution for that, so fix will be in next update, if you'd like to use digit grouping symbol again :smile:.
